# -*- coding: utf-8 -*-
"""analiseexploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yq4HgByjVC6IDy13pJm80dXD8AmPNUGv

Importing Libraries
"""

import pandas as pd
import numpy as np
import datetime as dt

"""Uploading Data"""

df = pd.read_csv('/content/netflix daily top 10.csv')

df.head()

df.tail()

df.shape

df.describe()

display(df)

inicio = pd.to_datetime(df['As of']).dt.date.min()
print(inicio)

fim = pd.to_datetime(df['As of']).dt.date.max()
print(fim)

df.info()

df.isnull().sum()

df.dtypes

df['Netflix Exclusive'].value_counts()

df.plot(kind= 'box', figsize= (10,6), subplots = True);

"""Checando os outliers"""

df[df['Days In Top 10'] >= 100]

df_excel = df[df['Days In Top 10'] >= 100]
df_excel.to_excel('Verificar.xlsx')

"""Entendendo melhor os dados"""

df.Title.value_counts()

df.Type.value_counts().plot(kind='bar');

df['Viewership Score'].hist();

df[df['Viewership Score'] == df['Viewership Score'].max()]